### ISSUE TITLE
sunglasses wrapping a fine-tuned Tranformer

### ISSUE THREAD

**Issue by gardsted** [centre-for-humanities-computing/DaCy#78] opened 2021-11-23 17:59 UTC
sunglasses wrapping a fine-tuned Tranformer is in tutorials section - missing an s.

**Comment by gardsted** [comment] 2021-11-23 18:00
https://github.com/centre-for-humanities-computing/DaCy, readme

**Comment by KennethEnevoldsen** [comment] 2021-11-24 11:02
Sorry I am unsure what is meant by this issue? The sunglasses renders as intended at least on my system. It that is not the case on your system I would very much appreciate a pull request with the corrected emoji.


<img width="752" alt="Screenshot 2021-11-24 at 12 00 16" src="https://user-images.githubusercontent.com/23721977/143226394-e4fd4d59-dee0-4e34-b0b7-82244dcb869b.png">

**Comment by gardsted** [comment] 2021-11-28 16:43
It was just a missing 's' in Transformer spelling.
If it is to be spelled Tranformer, please disregard my message.

**Comment by KennethEnevoldsen** [comment] 2021-11-28 21:15
Thanks for this @gardsted.I believe it should be spelled without an 's' given that it is singular. I will close this issue but I very much appreciate corrections to the documentation.

**Closed by KennethEnevoldsen** 2021-11-28 21:15 UTC
Labels: documentation
